title: Voice Actor Languages

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          languages:
            label: Languages
            type: structure
            fields:
              title:
                label: Title
                type: text
              id:
                label: id
                type: slug

  sidebar:
    width: 1/3
    fields:
      languageFlags:
        label: Language Flags
        type: files
        multiple: true
        upload:
          accept: image/*

